apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mednote-api
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  labels:
    app: mednote-api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
