apiVersion: apps/v1
kind: Deployment
metadata:
  name: mednote-ui-deployment
  labels: 
    app: mednote-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mednote-ui
  template:
    metadata:
      labels:
        app: mednote-ui
    spec:
      containers:
        - name : mednote-ui
          image: registry.gitlab.com/rsdevelopment/vuejs/mednote-ui/arm64:0.1 
          ports:
            - containerPort: 80
          env:
            - name: VUE_APP_MEDNOTE_UI_URL
              valueFrom:
                configMapKeyRef:
                  name: mednote-ui-config
                  key: mednote_ui_url
            - name: VUE_APP_MEDNOTE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: mednote-ui-config
                  key: mednote_api_url
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
