apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-7.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-7.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-7.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
- democratic-csi-iscsi-namespace.yaml
- democratic-csi-iscsi-application.yaml
# renovate: datasource=github-releases depName=pfnet-research/meta-fuse-csi-plugin
- https://raw.githubusercontent.com/pfnet-research/meta-fuse-csi-plugin/v0.1.0/deploy/csi-driver-daemonset.yaml
# renovate: datasource=github-releases depName=pfnet-research/meta-fuse-csi-plugin
- https://raw.githubusercontent.com/pfnet-research/meta-fuse-csi-plugin/v0.1.0/deploy/csi-driver.yaml

images:
 - name: ghcr.io/pfnet-research/meta-fuse-csi-plugin/meta-fuse-csi-plugin
# renovate: datasource=docker depName=ghcr.io/pfnet-research/meta-fuse-csi-plugin/meta-fuse-csi-plugin
   newTag: v0.1.0

patches:
  - target:
      kind: Namespace
      name: mfcp-system
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/enforce: privileged
