apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: nixos-config-runner
  namespace: actions-runner-system
spec:
  replicas: 4
  template:
    spec:
      repository: rszamszur/nixos-config