apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-master
  name: postgres-master
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-master
