apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master
  labels:
    app: postgres-master
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi
