kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nix-cache
  namespace: gha-runner-nixos-config
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi