apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-nixos-config
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: 0.8.2
    helm:
      version: v3
      values: |-
        githubConfigUrl: "https://github.com/rszamszur/nixos-config"
        githubConfigSecret: gha-runner-nixos-config-secret

        minRunners: 4
        maxRunners: 20

        runnerScaleSetName: pve-talos

        controllerServiceAccount:
          namespace: gha-runner-controller
          name: gha-runner-controller-gha-rs-controller

        containerMode:
          type: "dind"
        
        template:
          spec:
            initContainers:
            - name: init-dind-externals
              image: ghcr.io/rszamszur/actions-runner:latest
              command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
              volumeMounts:
                - name: dind-externals
                  mountPath: /home/runner/tmpDir
            containers:
            - name: runner
              image: ghcr.io/rszamszur/actions-runner:latest
              command: ["/home/runner/run.sh"]
              env:
                - name: DOCKER_HOST
                  value: unix:///run/docker/docker.sock
                - name: USER
                  value: runner
              volumeMounts:
                - name: work
                  mountPath: /home/runner/_work
                - name: dind-sock
                  mountPath: /run/docker
                  readOnly: true
            - name: dind
              image: docker:dind
              args:
                - dockerd
                - --host=unix:///run/docker/docker.sock
                - --group=$(DOCKER_GROUP_GID)
              env:
                - name: DOCKER_GROUP_GID
                  value: "123"
              securityContext:
                privileged: true
              volumeMounts:
                - name: work
                  mountPath: /home/runner/_work
                - name: dind-sock
                  mountPath: /run/docker
                - name: dind-externals
                  mountPath: /home/runner/externals
            volumes:
            - name: work
              emptyDir: {}
            - name: dind-sock
              emptyDir: {}
            - name: dind-externals
              emptyDir: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 5m
  destination:
    namespace: gha-runner-nixos-config
    server: https://kubernetes.default.svc
