apiVersion: v1
data:
  config: |
    Host nixremote
         # Prevent using ssh-agent or another keyfile, useful for testing
         IdentitiesOnly yes
         IdentityFile ~/.ssh/gh-runners
         User nixremote
         HostName 192.168.20.67
         Port 22
  known_hosts: |
    192.168.20.67 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ6ooKoU5SaAooFFpMS1HVdFduq6HwE5vrzVUuhZ40be
    192.168.20.67 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDhvXAkQnv13hp7CzUMdr/RH3sw/ZJ1+weBqE3DMi6Ddg1qQv2PSHR4MTx8iEIReTV+asnU8m1Kt7RBk3kFO89LzyHI+VGL7ab460mWBdFxBS9o4e5SH43+Hh6eHhGWHNETw7rRRawp6VZYuMcj1IQbYaoJujF4i1U9vjYlHjriZR1Omt4E34SIddvc4DbDD/q2Sd83Y7Q0XF3rjuoloyN1VdUGvhkkhVMjtdVs3TWYbjQvJhffe2lVMlOFlLvz05VTY2OyC67tG0oJ3QQZILx/gzqiEqaP4fbTXpMVxykvPKfJ2C7aNiJfzW51TJDoC2ropJtnXl0rEa2l449hYb8+F0DMsHn+lcrU+wBwkaQWO+V5zk/jNpdC8rFtNWuoojIleBzt1GW06tmrA5u6BSIVnt6z2k8xaTLDUhs0Xgqab0TKlxgk2qlFlXQAIS+cfjXY8FKVqgbu5pCknOC67GIoPYT3So07q62ljGvgqfXAGmCx0n4+2zjSEBEu79pBs6fAe6eqMhdaDMv60EgtxDfT2aoiPVvlOMUSSgyIzk5Makxste5+yB4Feq8RZVflB2c3oyJBfLWWG/+e9b3EFRoyDlpxz0kL7GOSUDqMghrmjn5bFf2vEScQEIjPdDzCSchFvNUUmEAgp6M0DynrdBsNpCC8gTsPBNrmEbqv64Ws6Q==
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: gha-runner-nixos-config
