apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stocker-data
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  labels:
    app: stocker
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

