apiVersion: batch/v1
kind: Job
metadata:
  generateName: stocker-job-
spec:
  template:
    spec:
      containers:
        - name : stocker-test
          image: registry.gitlab.com/rsdevelopment/python/stocker/arm64:0.2
          command: ['/bin/bash', '-c', 'mkdir /mnt/$HOSTNAME && stocker --disable-file-log run -c /mnt/$STOCKER_CONFIG_DIR -o /mnt/$HOSTNAME backtests']
          volumeMounts:
            - mountPath: /mnt
              name: content
            - mountPath: /root/.stocker
              name: settings
      restartPolicy: Never
      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: stocker-data
        - name: settings
          secret:
            secretName: stocker-secrets
  backoffLimit: 0

